/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.bPMN_translator.BPMN_translatorFactory
 * @model kind="package"
 * @generated
 */
public interface BPMN_translatorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bPMN_translator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/BPMN_translator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bPMN_translator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BPMN_translatorPackage eINSTANCE = org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.ModelImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.XmlImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
   * @generated
   */
  int XML = 1;

  /**
   * The feature id for the '<em><b>Prova</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML__PROVA = 0;

  /**
   * The number of structural features of the '<em>Xml</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.elementImpl <em>element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.elementImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement()
   * @generated
   */
  int ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Open</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__OPEN = 0;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__CONTENTS = 1;

  /**
   * The feature id for the '<em><b>Close tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__CLOSE_TAG = 2;

  /**
   * The number of structural features of the '<em>element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.contentImpl <em>content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.contentImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcontent()
   * @generated
   */
  int CONTENT = 3;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__BODY = 1;

  /**
   * The feature id for the '<em><b>Keywords</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__KEYWORDS = 2;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__DATA = 3;

  /**
   * The number of structural features of the '<em>content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.OpenImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
   * @generated
   */
  int OPEN = 4;

  /**
   * The feature id for the '<em><b>Head</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__HEAD = 0;

  /**
   * The feature id for the '<em><b>Keywords</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__KEYWORDS = 1;

  /**
   * The feature id for the '<em><b>Head1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__HEAD1 = 2;

  /**
   * The feature id for the '<em><b>Keywords1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__KEYWORDS1 = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__VALUE = 4;

  /**
   * The number of structural features of the '<em>Open</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.SingletonImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
   * @generated
   */
  int SINGLETON = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON__VALUE = 0;

  /**
   * The number of structural features of the '<em>Singleton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.CloseImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
   * @generated
   */
  int CLOSE = 6;

  /**
   * The number of structural features of the '<em>Close</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.element_valueImpl <em>element value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.element_valueImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement_value()
   * @generated
   */
  int ELEMENT_VALUE = 7;

  /**
   * The feature id for the '<em><b>Open</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_VALUE__OPEN = ELEMENT__OPEN;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_VALUE__CONTENTS = ELEMENT__CONTENTS;

  /**
   * The feature id for the '<em><b>Close tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_VALUE__CLOSE_TAG = ELEMENT__CLOSE_TAG;

  /**
   * The feature id for the '<em><b>Singleton tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_VALUE__SINGLETON_TAG = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>element value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_VALUE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Xml <em>Xml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xml</em>'.
   * @see org.xtext.bPMN_translator.Xml
   * @generated
   */
  EClass getXml();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Xml#getProva <em>Prova</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prova</em>'.
   * @see org.xtext.bPMN_translator.Xml#getProva()
   * @see #getXml()
   * @generated
   */
  EReference getXml_Prova();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.element <em>element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>element</em>'.
   * @see org.xtext.bPMN_translator.element
   * @generated
   */
  EClass getelement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getOpen <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Open</em>'.
   * @see org.xtext.bPMN_translator.element#getOpen()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Open();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see org.xtext.bPMN_translator.element#getContents()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Contents();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getClose_tag <em>Close tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Close tag</em>'.
   * @see org.xtext.bPMN_translator.element#getClose_tag()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Close_tag();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.content <em>content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>content</em>'.
   * @see org.xtext.bPMN_translator.content
   * @generated
   */
  EClass getcontent();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.content#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.bPMN_translator.content#getElement()
   * @see #getcontent()
   * @generated
   */
  EReference getcontent_Element();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Body</em>'.
   * @see org.xtext.bPMN_translator.content#getBody()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Body();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getKeywords <em>Keywords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords</em>'.
   * @see org.xtext.bPMN_translator.content#getKeywords()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Keywords();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Data</em>'.
   * @see org.xtext.bPMN_translator.content#getData()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Open <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open</em>'.
   * @see org.xtext.bPMN_translator.Open
   * @generated
   */
  EClass getOpen();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getHead <em>Head</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Head</em>'.
   * @see org.xtext.bPMN_translator.Open#getHead()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Head();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getKeywords <em>Keywords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords</em>'.
   * @see org.xtext.bPMN_translator.Open#getKeywords()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Keywords();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getHead1 <em>Head1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Head1</em>'.
   * @see org.xtext.bPMN_translator.Open#getHead1()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Head1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getKeywords1 <em>Keywords1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords1</em>'.
   * @see org.xtext.bPMN_translator.Open#getKeywords1()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Keywords1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Open#getValue()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Singleton <em>Singleton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Singleton</em>'.
   * @see org.xtext.bPMN_translator.Singleton
   * @generated
   */
  EClass getSingleton();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Singleton#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Singleton#getValue()
   * @see #getSingleton()
   * @generated
   */
  EAttribute getSingleton_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Close <em>Close</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close</em>'.
   * @see org.xtext.bPMN_translator.Close
   * @generated
   */
  EClass getClose();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.element_value <em>element value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>element value</em>'.
   * @see org.xtext.bPMN_translator.element_value
   * @generated
   */
  EClass getelement_value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element_value#getSingleton_tag <em>Singleton tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Singleton tag</em>'.
   * @see org.xtext.bPMN_translator.element_value#getSingleton_tag()
   * @see #getelement_value()
   * @generated
   */
  EReference getelement_value_Singleton_tag();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BPMN_translatorFactory getBPMN_translatorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.ModelImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.XmlImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
     * @generated
     */
    EClass XML = eINSTANCE.getXml();

    /**
     * The meta object literal for the '<em><b>Prova</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XML__PROVA = eINSTANCE.getXml_Prova();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.elementImpl <em>element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.elementImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getelement();

    /**
     * The meta object literal for the '<em><b>Open</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__OPEN = eINSTANCE.getelement_Open();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__CONTENTS = eINSTANCE.getelement_Contents();

    /**
     * The meta object literal for the '<em><b>Close tag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__CLOSE_TAG = eINSTANCE.getelement_Close_tag();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.contentImpl <em>content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.contentImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcontent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getcontent();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT__ELEMENT = eINSTANCE.getcontent_Element();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__BODY = eINSTANCE.getcontent_Body();

    /**
     * The meta object literal for the '<em><b>Keywords</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__KEYWORDS = eINSTANCE.getcontent_Keywords();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__DATA = eINSTANCE.getcontent_Data();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.OpenImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
     * @generated
     */
    EClass OPEN = eINSTANCE.getOpen();

    /**
     * The meta object literal for the '<em><b>Head</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__HEAD = eINSTANCE.getOpen_Head();

    /**
     * The meta object literal for the '<em><b>Keywords</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__KEYWORDS = eINSTANCE.getOpen_Keywords();

    /**
     * The meta object literal for the '<em><b>Head1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__HEAD1 = eINSTANCE.getOpen_Head1();

    /**
     * The meta object literal for the '<em><b>Keywords1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__KEYWORDS1 = eINSTANCE.getOpen_Keywords1();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__VALUE = eINSTANCE.getOpen_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.SingletonImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
     * @generated
     */
    EClass SINGLETON = eINSTANCE.getSingleton();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLETON__VALUE = eINSTANCE.getSingleton_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.CloseImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
     * @generated
     */
    EClass CLOSE = eINSTANCE.getClose();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.element_valueImpl <em>element value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.element_valueImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement_value()
     * @generated
     */
    EClass ELEMENT_VALUE = eINSTANCE.getelement_value();

    /**
     * The meta object literal for the '<em><b>Singleton tag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT_VALUE__SINGLETON_TAG = eINSTANCE.getelement_value_Singleton_tag();

  }

} //BPMN_translatorPackage
