/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.bPMN_translator.BPMN_translatorFactory
 * @model kind="package"
 * @generated
 */
public interface BPMN_translatorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bPMN_translator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/BPMN_translator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bPMN_translator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BPMN_translatorPackage eINSTANCE = org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.ModelImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.XmlImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
   * @generated
   */
  int XML = 1;

  /**
   * The feature id for the '<em><b>Opening tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML__OPENING_TAG = 0;

  /**
   * The number of structural features of the '<em>Xml</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.OpeningImpl <em>Opening</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.OpeningImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpening()
   * @generated
   */
  int OPENING = 2;

  /**
   * The feature id for the '<em><b>Prova</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENING__PROVA = 0;

  /**
   * The feature id for the '<em><b>Prova1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENING__PROVA1 = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENING__VALUE = 2;

  /**
   * The number of structural features of the '<em>Opening</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.OpenImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
   * @generated
   */
  int OPEN = 3;

  /**
   * The number of structural features of the '<em>Open</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.SingletonImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
   * @generated
   */
  int SINGLETON = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON__VALUE = 0;

  /**
   * The number of structural features of the '<em>Singleton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.CloseImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
   * @generated
   */
  int CLOSE = 5;

  /**
   * The number of structural features of the '<em>Close</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.OpensImpl <em>Opens</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.OpensImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpens()
   * @generated
   */
  int OPENS = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENS__VALUE = OPEN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Prova</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENS__PROVA = OPEN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Opens</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPENS_FEATURE_COUNT = OPEN_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Xml <em>Xml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xml</em>'.
   * @see org.xtext.bPMN_translator.Xml
   * @generated
   */
  EClass getXml();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Xml#getOpening_tag <em>Opening tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Opening tag</em>'.
   * @see org.xtext.bPMN_translator.Xml#getOpening_tag()
   * @see #getXml()
   * @generated
   */
  EReference getXml_Opening_tag();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Opening <em>Opening</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Opening</em>'.
   * @see org.xtext.bPMN_translator.Opening
   * @generated
   */
  EClass getOpening();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Opening#getProva <em>Prova</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prova</em>'.
   * @see org.xtext.bPMN_translator.Opening#getProva()
   * @see #getOpening()
   * @generated
   */
  EReference getOpening_Prova();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Opening#getProva1 <em>Prova1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prova1</em>'.
   * @see org.xtext.bPMN_translator.Opening#getProva1()
   * @see #getOpening()
   * @generated
   */
  EReference getOpening_Prova1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Opening#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Opening#getValue()
   * @see #getOpening()
   * @generated
   */
  EAttribute getOpening_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Open <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open</em>'.
   * @see org.xtext.bPMN_translator.Open
   * @generated
   */
  EClass getOpen();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Singleton <em>Singleton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Singleton</em>'.
   * @see org.xtext.bPMN_translator.Singleton
   * @generated
   */
  EClass getSingleton();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Singleton#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Singleton#getValue()
   * @see #getSingleton()
   * @generated
   */
  EAttribute getSingleton_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Close <em>Close</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close</em>'.
   * @see org.xtext.bPMN_translator.Close
   * @generated
   */
  EClass getClose();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Opens <em>Opens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Opens</em>'.
   * @see org.xtext.bPMN_translator.Opens
   * @generated
   */
  EClass getOpens();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Opens#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Opens#getValue()
   * @see #getOpens()
   * @generated
   */
  EAttribute getOpens_Value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Opens#getProva <em>Prova</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prova</em>'.
   * @see org.xtext.bPMN_translator.Opens#getProva()
   * @see #getOpens()
   * @generated
   */
  EReference getOpens_Prova();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BPMN_translatorFactory getBPMN_translatorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.ModelImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.XmlImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
     * @generated
     */
    EClass XML = eINSTANCE.getXml();

    /**
     * The meta object literal for the '<em><b>Opening tag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XML__OPENING_TAG = eINSTANCE.getXml_Opening_tag();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.OpeningImpl <em>Opening</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.OpeningImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpening()
     * @generated
     */
    EClass OPENING = eINSTANCE.getOpening();

    /**
     * The meta object literal for the '<em><b>Prova</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPENING__PROVA = eINSTANCE.getOpening_Prova();

    /**
     * The meta object literal for the '<em><b>Prova1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPENING__PROVA1 = eINSTANCE.getOpening_Prova1();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPENING__VALUE = eINSTANCE.getOpening_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.OpenImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
     * @generated
     */
    EClass OPEN = eINSTANCE.getOpen();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.SingletonImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
     * @generated
     */
    EClass SINGLETON = eINSTANCE.getSingleton();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLETON__VALUE = eINSTANCE.getSingleton_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.CloseImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
     * @generated
     */
    EClass CLOSE = eINSTANCE.getClose();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.OpensImpl <em>Opens</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.OpensImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpens()
     * @generated
     */
    EClass OPENS = eINSTANCE.getOpens();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPENS__VALUE = eINSTANCE.getOpens_Value();

    /**
     * The meta object literal for the '<em><b>Prova</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPENS__PROVA = eINSTANCE.getOpens_Prova();

  }

} //BPMN_translatorPackage
