/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.bPMN_translator.BPMN_translatorFactory
 * @model kind="package"
 * @generated
 */
public interface BPMN_translatorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bPMN_translator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/BPMN_translator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bPMN_translator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BPMN_translatorPackage eINSTANCE = org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.ModelImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.XmlImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
   * @generated
   */
  int XML = 1;

  /**
   * The feature id for the '<em><b>Prova</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML__PROVA = 0;

  /**
   * The number of structural features of the '<em>Xml</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XML_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.elementImpl <em>element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.elementImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement()
   * @generated
   */
  int ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Open</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__OPEN = 0;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__CONTENTS = 1;

  /**
   * The feature id for the '<em><b>Close tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__CLOSE_TAG = 2;

  /**
   * The feature id for the '<em><b>Singleton tag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__SINGLETON_TAG = 3;

  /**
   * The number of structural features of the '<em>element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.contentImpl <em>content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.contentImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcontent()
   * @generated
   */
  int CONTENT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Codex</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__CODEX = 1;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__BODY = 3;

  /**
   * The feature id for the '<em><b>Keywords</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__KEYWORDS = 4;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__DATA = 5;

  /**
   * The number of structural features of the '<em>content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.OpenImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
   * @generated
   */
  int OPEN = 4;

  /**
   * The feature id for the '<em><b>Head</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__HEAD = 0;

  /**
   * The feature id for the '<em><b>Keywords</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__KEYWORDS = 1;

  /**
   * The feature id for the '<em><b>Head1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__HEAD1 = 2;

  /**
   * The feature id for the '<em><b>Keywords1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__KEYWORDS1 = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__VALUE = 4;

  /**
   * The number of structural features of the '<em>Open</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.SingletonImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
   * @generated
   */
  int SINGLETON = 5;

  /**
   * The feature id for the '<em><b>Keywords</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON__KEYWORDS = 0;

  /**
   * The feature id for the '<em><b>Keywords1</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON__KEYWORDS1 = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON__VALUE = 2;

  /**
   * The number of structural features of the '<em>Singleton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLETON_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.CloseImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
   * @generated
   */
  int CLOSE = 6;

  /**
   * The number of structural features of the '<em>Close</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.codexImpl <em>codex</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.codexImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcodex()
   * @generated
   */
  int CODEX = 7;

  /**
   * The feature id for the '<em><b>Device code</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODEX__DEVICE_CODE = 0;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODEX__PROTOCOL = 1;

  /**
   * The feature id for the '<em><b>Sensor code</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODEX__SENSOR_CODE = 2;

  /**
   * The number of structural features of the '<em>codex</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODEX_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.deviceImpl <em>device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.deviceImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getdevice()
   * @generated
   */
  int DEVICE = 8;

  /**
   * The feature id for the '<em><b>Device</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__DEVICE = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__ID = 1;

  /**
   * The number of structural features of the '<em>device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.protocolImpl <em>protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.protocolImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getprotocol()
   * @generated
   */
  int PROTOCOL = 9;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL__PNAME = 0;

  /**
   * The feature id for the '<em><b>Mqtt data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL__MQTT_DATA = 1;

  /**
   * The feature id for the '<em><b>Mqtt device</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL__MQTT_DEVICE = 2;

  /**
   * The number of structural features of the '<em>protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.mqtt_dataImpl <em>mqtt data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.mqtt_dataImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_data()
   * @generated
   */
  int MQTT_DATA = 10;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__PNAME = 0;

  /**
   * The feature id for the '<em><b>Broker user</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__BROKER_USER = 1;

  /**
   * The feature id for the '<em><b>Broker password</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__BROKER_PASSWORD = 2;

  /**
   * The feature id for the '<em><b>Broker</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__BROKER = 3;

  /**
   * The feature id for the '<em><b>Mqtt network data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__MQTT_NETWORK_DATA = 4;

  /**
   * The feature id for the '<em><b>Subtopics</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__SUBTOPICS = 5;

  /**
   * The feature id for the '<em><b>Pubtopics</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__PUBTOPICS = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA__VALUE = 7;

  /**
   * The number of structural features of the '<em>mqtt data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DATA_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.mqtt_network_dataImpl <em>mqtt network data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.mqtt_network_dataImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_network_data()
   * @generated
   */
  int MQTT_NETWORK_DATA = 11;

  /**
   * The feature id for the '<em><b>Ssid</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_NETWORK_DATA__SSID = 0;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_NETWORK_DATA__PASSWORD = 1;

  /**
   * The number of structural features of the '<em>mqtt network data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_NETWORK_DATA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.mqtt_deviceImpl <em>mqtt device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.mqtt_deviceImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_device()
   * @generated
   */
  int MQTT_DEVICE = 12;

  /**
   * The feature id for the '<em><b>Dname</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DEVICE__DNAME = 0;

  /**
   * The number of structural features of the '<em>mqtt device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MQTT_DEVICE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.sensorImpl <em>sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.sensorImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getsensor()
   * @generated
   */
  int SENSOR = 13;

  /**
   * The feature id for the '<em><b>Sname</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SNAME = 0;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SENSOR = 1;

  /**
   * The number of structural features of the '<em>sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bPMN_translator.impl.sensor_dataImpl <em>sensor data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bPMN_translator.impl.sensor_dataImpl
   * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getsensor_data()
   * @generated
   */
  int SENSOR_DATA = 14;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DATA__PNAME = 0;

  /**
   * The feature id for the '<em><b>Pins</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DATA__PINS = 1;

  /**
   * The feature id for the '<em><b>Sensor id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DATA__SENSOR_ID = 2;

  /**
   * The number of structural features of the '<em>sensor data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DATA_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model</em>'.
   * @see org.xtext.bPMN_translator.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Xml <em>Xml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xml</em>'.
   * @see org.xtext.bPMN_translator.Xml
   * @generated
   */
  EClass getXml();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.Xml#getProva <em>Prova</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prova</em>'.
   * @see org.xtext.bPMN_translator.Xml#getProva()
   * @see #getXml()
   * @generated
   */
  EReference getXml_Prova();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.element <em>element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>element</em>'.
   * @see org.xtext.bPMN_translator.element
   * @generated
   */
  EClass getelement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getOpen <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Open</em>'.
   * @see org.xtext.bPMN_translator.element#getOpen()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Open();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see org.xtext.bPMN_translator.element#getContents()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Contents();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getClose_tag <em>Close tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Close tag</em>'.
   * @see org.xtext.bPMN_translator.element#getClose_tag()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Close_tag();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.element#getSingleton_tag <em>Singleton tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Singleton tag</em>'.
   * @see org.xtext.bPMN_translator.element#getSingleton_tag()
   * @see #getelement()
   * @generated
   */
  EReference getelement_Singleton_tag();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.content <em>content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>content</em>'.
   * @see org.xtext.bPMN_translator.content
   * @generated
   */
  EClass getcontent();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Type</em>'.
   * @see org.xtext.bPMN_translator.content#getType()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.content#getCodex <em>Codex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Codex</em>'.
   * @see org.xtext.bPMN_translator.content#getCodex()
   * @see #getcontent()
   * @generated
   */
  EReference getcontent_Codex();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.content#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.bPMN_translator.content#getElement()
   * @see #getcontent()
   * @generated
   */
  EReference getcontent_Element();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Body</em>'.
   * @see org.xtext.bPMN_translator.content#getBody()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Body();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getKeywords <em>Keywords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords</em>'.
   * @see org.xtext.bPMN_translator.content#getKeywords()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Keywords();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.content#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Data</em>'.
   * @see org.xtext.bPMN_translator.content#getData()
   * @see #getcontent()
   * @generated
   */
  EAttribute getcontent_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Open <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open</em>'.
   * @see org.xtext.bPMN_translator.Open
   * @generated
   */
  EClass getOpen();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getHead <em>Head</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Head</em>'.
   * @see org.xtext.bPMN_translator.Open#getHead()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Head();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getKeywords <em>Keywords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords</em>'.
   * @see org.xtext.bPMN_translator.Open#getKeywords()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Keywords();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getHead1 <em>Head1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Head1</em>'.
   * @see org.xtext.bPMN_translator.Open#getHead1()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Head1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getKeywords1 <em>Keywords1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords1</em>'.
   * @see org.xtext.bPMN_translator.Open#getKeywords1()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Keywords1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Open#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Open#getValue()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Singleton <em>Singleton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Singleton</em>'.
   * @see org.xtext.bPMN_translator.Singleton
   * @generated
   */
  EClass getSingleton();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Singleton#getKeywords <em>Keywords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords</em>'.
   * @see org.xtext.bPMN_translator.Singleton#getKeywords()
   * @see #getSingleton()
   * @generated
   */
  EAttribute getSingleton_Keywords();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Singleton#getKeywords1 <em>Keywords1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keywords1</em>'.
   * @see org.xtext.bPMN_translator.Singleton#getKeywords1()
   * @see #getSingleton()
   * @generated
   */
  EAttribute getSingleton_Keywords1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.Singleton#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.Singleton#getValue()
   * @see #getSingleton()
   * @generated
   */
  EAttribute getSingleton_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.Close <em>Close</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close</em>'.
   * @see org.xtext.bPMN_translator.Close
   * @generated
   */
  EClass getClose();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.codex <em>codex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>codex</em>'.
   * @see org.xtext.bPMN_translator.codex
   * @generated
   */
  EClass getcodex();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.codex#getDevice_code <em>Device code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Device code</em>'.
   * @see org.xtext.bPMN_translator.codex#getDevice_code()
   * @see #getcodex()
   * @generated
   */
  EReference getcodex_Device_code();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.codex#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Protocol</em>'.
   * @see org.xtext.bPMN_translator.codex#getProtocol()
   * @see #getcodex()
   * @generated
   */
  EReference getcodex_Protocol();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.codex#getSensor_code <em>Sensor code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensor code</em>'.
   * @see org.xtext.bPMN_translator.codex#getSensor_code()
   * @see #getcodex()
   * @generated
   */
  EReference getcodex_Sensor_code();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.device <em>device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>device</em>'.
   * @see org.xtext.bPMN_translator.device
   * @generated
   */
  EClass getdevice();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.device#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Device</em>'.
   * @see org.xtext.bPMN_translator.device#getDevice()
   * @see #getdevice()
   * @generated
   */
  EAttribute getdevice_Device();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.device#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Id</em>'.
   * @see org.xtext.bPMN_translator.device#getId()
   * @see #getdevice()
   * @generated
   */
  EAttribute getdevice_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.protocol <em>protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>protocol</em>'.
   * @see org.xtext.bPMN_translator.protocol
   * @generated
   */
  EClass getprotocol();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.protocol#getPname <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pname</em>'.
   * @see org.xtext.bPMN_translator.protocol#getPname()
   * @see #getprotocol()
   * @generated
   */
  EAttribute getprotocol_Pname();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.protocol#getMqtt_data <em>Mqtt data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mqtt data</em>'.
   * @see org.xtext.bPMN_translator.protocol#getMqtt_data()
   * @see #getprotocol()
   * @generated
   */
  EReference getprotocol_Mqtt_data();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.protocol#getMqtt_device <em>Mqtt device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mqtt device</em>'.
   * @see org.xtext.bPMN_translator.protocol#getMqtt_device()
   * @see #getprotocol()
   * @generated
   */
  EReference getprotocol_Mqtt_device();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.mqtt_data <em>mqtt data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>mqtt data</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data
   * @generated
   */
  EClass getmqtt_data();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getPname <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pname</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getPname()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Pname();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getBroker_user <em>Broker user</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Broker user</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getBroker_user()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Broker_user();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getBroker_password <em>Broker password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Broker password</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getBroker_password()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Broker_password();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getBroker <em>Broker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Broker</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getBroker()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Broker();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.mqtt_data#getMqtt_network_data <em>Mqtt network data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mqtt network data</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getMqtt_network_data()
   * @see #getmqtt_data()
   * @generated
   */
  EReference getmqtt_data_Mqtt_network_data();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getSubtopics <em>Subtopics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Subtopics</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getSubtopics()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Subtopics();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getPubtopics <em>Pubtopics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pubtopics</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getPubtopics()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Pubtopics();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_data#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.bPMN_translator.mqtt_data#getValue()
   * @see #getmqtt_data()
   * @generated
   */
  EAttribute getmqtt_data_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.mqtt_network_data <em>mqtt network data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>mqtt network data</em>'.
   * @see org.xtext.bPMN_translator.mqtt_network_data
   * @generated
   */
  EClass getmqtt_network_data();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_network_data#getSsid <em>Ssid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ssid</em>'.
   * @see org.xtext.bPMN_translator.mqtt_network_data#getSsid()
   * @see #getmqtt_network_data()
   * @generated
   */
  EAttribute getmqtt_network_data_Ssid();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_network_data#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Password</em>'.
   * @see org.xtext.bPMN_translator.mqtt_network_data#getPassword()
   * @see #getmqtt_network_data()
   * @generated
   */
  EAttribute getmqtt_network_data_Password();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.mqtt_device <em>mqtt device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>mqtt device</em>'.
   * @see org.xtext.bPMN_translator.mqtt_device
   * @generated
   */
  EClass getmqtt_device();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.mqtt_device#getDname <em>Dname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Dname</em>'.
   * @see org.xtext.bPMN_translator.mqtt_device#getDname()
   * @see #getmqtt_device()
   * @generated
   */
  EAttribute getmqtt_device_Dname();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.sensor <em>sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>sensor</em>'.
   * @see org.xtext.bPMN_translator.sensor
   * @generated
   */
  EClass getsensor();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.sensor#getSname <em>Sname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Sname</em>'.
   * @see org.xtext.bPMN_translator.sensor#getSname()
   * @see #getsensor()
   * @generated
   */
  EAttribute getsensor_Sname();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bPMN_translator.sensor#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensor</em>'.
   * @see org.xtext.bPMN_translator.sensor#getSensor()
   * @see #getsensor()
   * @generated
   */
  EReference getsensor_Sensor();

  /**
   * Returns the meta object for class '{@link org.xtext.bPMN_translator.sensor_data <em>sensor data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>sensor data</em>'.
   * @see org.xtext.bPMN_translator.sensor_data
   * @generated
   */
  EClass getsensor_data();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.sensor_data#getPname <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pname</em>'.
   * @see org.xtext.bPMN_translator.sensor_data#getPname()
   * @see #getsensor_data()
   * @generated
   */
  EAttribute getsensor_data_Pname();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.sensor_data#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pins</em>'.
   * @see org.xtext.bPMN_translator.sensor_data#getPins()
   * @see #getsensor_data()
   * @generated
   */
  EAttribute getsensor_data_Pins();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.bPMN_translator.sensor_data#getSensor_id <em>Sensor id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Sensor id</em>'.
   * @see org.xtext.bPMN_translator.sensor_data#getSensor_id()
   * @see #getsensor_data()
   * @generated
   */
  EAttribute getsensor_data_Sensor_id();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BPMN_translatorFactory getBPMN_translatorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.ModelImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.XmlImpl <em>Xml</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.XmlImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getXml()
     * @generated
     */
    EClass XML = eINSTANCE.getXml();

    /**
     * The meta object literal for the '<em><b>Prova</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XML__PROVA = eINSTANCE.getXml_Prova();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.elementImpl <em>element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.elementImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getelement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getelement();

    /**
     * The meta object literal for the '<em><b>Open</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__OPEN = eINSTANCE.getelement_Open();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__CONTENTS = eINSTANCE.getelement_Contents();

    /**
     * The meta object literal for the '<em><b>Close tag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__CLOSE_TAG = eINSTANCE.getelement_Close_tag();

    /**
     * The meta object literal for the '<em><b>Singleton tag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__SINGLETON_TAG = eINSTANCE.getelement_Singleton_tag();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.contentImpl <em>content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.contentImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcontent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getcontent();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__TYPE = eINSTANCE.getcontent_Type();

    /**
     * The meta object literal for the '<em><b>Codex</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT__CODEX = eINSTANCE.getcontent_Codex();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT__ELEMENT = eINSTANCE.getcontent_Element();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__BODY = eINSTANCE.getcontent_Body();

    /**
     * The meta object literal for the '<em><b>Keywords</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__KEYWORDS = eINSTANCE.getcontent_Keywords();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__DATA = eINSTANCE.getcontent_Data();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.OpenImpl <em>Open</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.OpenImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getOpen()
     * @generated
     */
    EClass OPEN = eINSTANCE.getOpen();

    /**
     * The meta object literal for the '<em><b>Head</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__HEAD = eINSTANCE.getOpen_Head();

    /**
     * The meta object literal for the '<em><b>Keywords</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__KEYWORDS = eINSTANCE.getOpen_Keywords();

    /**
     * The meta object literal for the '<em><b>Head1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__HEAD1 = eINSTANCE.getOpen_Head1();

    /**
     * The meta object literal for the '<em><b>Keywords1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__KEYWORDS1 = eINSTANCE.getOpen_Keywords1();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__VALUE = eINSTANCE.getOpen_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.SingletonImpl <em>Singleton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.SingletonImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getSingleton()
     * @generated
     */
    EClass SINGLETON = eINSTANCE.getSingleton();

    /**
     * The meta object literal for the '<em><b>Keywords</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLETON__KEYWORDS = eINSTANCE.getSingleton_Keywords();

    /**
     * The meta object literal for the '<em><b>Keywords1</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLETON__KEYWORDS1 = eINSTANCE.getSingleton_Keywords1();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLETON__VALUE = eINSTANCE.getSingleton_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.CloseImpl <em>Close</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.CloseImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getClose()
     * @generated
     */
    EClass CLOSE = eINSTANCE.getClose();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.codexImpl <em>codex</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.codexImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getcodex()
     * @generated
     */
    EClass CODEX = eINSTANCE.getcodex();

    /**
     * The meta object literal for the '<em><b>Device code</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CODEX__DEVICE_CODE = eINSTANCE.getcodex_Device_code();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CODEX__PROTOCOL = eINSTANCE.getcodex_Protocol();

    /**
     * The meta object literal for the '<em><b>Sensor code</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CODEX__SENSOR_CODE = eINSTANCE.getcodex_Sensor_code();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.deviceImpl <em>device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.deviceImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getdevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getdevice();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__DEVICE = eINSTANCE.getdevice_Device();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__ID = eINSTANCE.getdevice_Id();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.protocolImpl <em>protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.protocolImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getprotocol()
     * @generated
     */
    EClass PROTOCOL = eINSTANCE.getprotocol();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTOCOL__PNAME = eINSTANCE.getprotocol_Pname();

    /**
     * The meta object literal for the '<em><b>Mqtt data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOL__MQTT_DATA = eINSTANCE.getprotocol_Mqtt_data();

    /**
     * The meta object literal for the '<em><b>Mqtt device</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOL__MQTT_DEVICE = eINSTANCE.getprotocol_Mqtt_device();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.mqtt_dataImpl <em>mqtt data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.mqtt_dataImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_data()
     * @generated
     */
    EClass MQTT_DATA = eINSTANCE.getmqtt_data();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__PNAME = eINSTANCE.getmqtt_data_Pname();

    /**
     * The meta object literal for the '<em><b>Broker user</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__BROKER_USER = eINSTANCE.getmqtt_data_Broker_user();

    /**
     * The meta object literal for the '<em><b>Broker password</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__BROKER_PASSWORD = eINSTANCE.getmqtt_data_Broker_password();

    /**
     * The meta object literal for the '<em><b>Broker</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__BROKER = eINSTANCE.getmqtt_data_Broker();

    /**
     * The meta object literal for the '<em><b>Mqtt network data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MQTT_DATA__MQTT_NETWORK_DATA = eINSTANCE.getmqtt_data_Mqtt_network_data();

    /**
     * The meta object literal for the '<em><b>Subtopics</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__SUBTOPICS = eINSTANCE.getmqtt_data_Subtopics();

    /**
     * The meta object literal for the '<em><b>Pubtopics</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__PUBTOPICS = eINSTANCE.getmqtt_data_Pubtopics();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DATA__VALUE = eINSTANCE.getmqtt_data_Value();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.mqtt_network_dataImpl <em>mqtt network data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.mqtt_network_dataImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_network_data()
     * @generated
     */
    EClass MQTT_NETWORK_DATA = eINSTANCE.getmqtt_network_data();

    /**
     * The meta object literal for the '<em><b>Ssid</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_NETWORK_DATA__SSID = eINSTANCE.getmqtt_network_data_Ssid();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_NETWORK_DATA__PASSWORD = eINSTANCE.getmqtt_network_data_Password();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.mqtt_deviceImpl <em>mqtt device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.mqtt_deviceImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getmqtt_device()
     * @generated
     */
    EClass MQTT_DEVICE = eINSTANCE.getmqtt_device();

    /**
     * The meta object literal for the '<em><b>Dname</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MQTT_DEVICE__DNAME = eINSTANCE.getmqtt_device_Dname();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.sensorImpl <em>sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.sensorImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getsensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getsensor();

    /**
     * The meta object literal for the '<em><b>Sname</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__SNAME = eINSTANCE.getsensor_Sname();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__SENSOR = eINSTANCE.getsensor_Sensor();

    /**
     * The meta object literal for the '{@link org.xtext.bPMN_translator.impl.sensor_dataImpl <em>sensor data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bPMN_translator.impl.sensor_dataImpl
     * @see org.xtext.bPMN_translator.impl.BPMN_translatorPackageImpl#getsensor_data()
     * @generated
     */
    EClass SENSOR_DATA = eINSTANCE.getsensor_data();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_DATA__PNAME = eINSTANCE.getsensor_data_Pname();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_DATA__PINS = eINSTANCE.getsensor_data_Pins();

    /**
     * The meta object literal for the '<em><b>Sensor id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_DATA__SENSOR_ID = eINSTANCE.getsensor_data_Sensor_id();

  }

} //BPMN_translatorPackage
