/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bPMN_translator.content#getProva <em>Prova</em>}</li>
 * </ul>
 *
 * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getcontent()
 * @model
 * @generated
 */
public interface content extends EObject
{
  /**
   * Returns the value of the '<em><b>Prova</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bPMN_translator.element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prova</em>' containment reference list.
   * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getcontent_Prova()
   * @model containment="true"
   * @generated
   */
  EList<element> getProva();

} // content
