/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>protocol device</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bPMN_translator.protocol_device#getProtocol_device <em>Protocol device</em>}</li>
 * </ul>
 *
 * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getprotocol_device()
 * @model
 * @generated
 */
public interface protocol_device extends EObject
{
  /**
   * Returns the value of the '<em><b>Protocol device</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bPMN_translator.sensor_data}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol device</em>' containment reference list.
   * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getprotocol_device_Protocol_device()
   * @model containment="true"
   * @generated
   */
  EList<sensor_data> getProtocol_device();

} // protocol_device
