/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bPMN_translator.sensor#getSname <em>Sname</em>}</li>
 *   <li>{@link org.xtext.bPMN_translator.sensor#getSensor <em>Sensor</em>}</li>
 * </ul>
 *
 * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getsensor()
 * @model
 * @generated
 */
public interface sensor extends EObject
{
  /**
   * Returns the value of the '<em><b>Sname</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sname</em>' attribute list.
   * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getsensor_Sname()
   * @model unique="false"
   * @generated
   */
  EList<String> getSname();

  /**
   * Returns the value of the '<em><b>Sensor</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bPMN_translator.sensor_data}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' containment reference list.
   * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getsensor_Sensor()
   * @model containment="true"
   * @generated
   */
  EList<sensor_data> getSensor();

} // sensor
