/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Singleton</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getSingleton()
 * @model
 * @generated
 */
public interface Singleton extends Tag
{
} // Singleton
