/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xml</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bPMN_translator.Xml#getOpening_tag <em>Opening tag</em>}</li>
 * </ul>
 *
 * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getXml()
 * @model
 * @generated
 */
public interface Xml extends EObject
{
  /**
   * Returns the value of the '<em><b>Opening tag</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bPMN_translator.Opening}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opening tag</em>' containment reference list.
   * @see org.xtext.bPMN_translator.BPMN_translatorPackage#getXml_Opening_tag()
   * @model containment="true"
   * @generated
   */
  EList<Opening> getOpening_tag();

} // Xml
