/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.bPMN_translator.BPMN_translatorPackage;
import org.xtext.bPMN_translator.mqtt_data;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>mqtt data</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class mqtt_dataImpl extends MinimalEObjectImpl.Container implements mqtt_data
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected mqtt_dataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BPMN_translatorPackage.Literals.MQTT_DATA;
  }

} //mqtt_dataImpl
