/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.bPMN_translator.BPMN_translatorPackage;
import org.xtext.bPMN_translator.mqtt_device;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>mqtt device</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bPMN_translator.impl.mqtt_deviceImpl#getProtocol_device <em>Protocol device</em>}</li>
 * </ul>
 *
 * @generated
 */
public class mqtt_deviceImpl extends MinimalEObjectImpl.Container implements mqtt_device
{
  /**
   * The cached value of the '{@link #getProtocol_device() <em>Protocol device</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtocol_device()
   * @generated
   * @ordered
   */
  protected EList<String> protocol_device;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected mqtt_deviceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BPMN_translatorPackage.Literals.MQTT_DEVICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getProtocol_device()
  {
    if (protocol_device == null)
    {
      protocol_device = new EDataTypeEList<String>(String.class, this, BPMN_translatorPackage.MQTT_DEVICE__PROTOCOL_DEVICE);
    }
    return protocol_device;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BPMN_translatorPackage.MQTT_DEVICE__PROTOCOL_DEVICE:
        return getProtocol_device();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BPMN_translatorPackage.MQTT_DEVICE__PROTOCOL_DEVICE:
        getProtocol_device().clear();
        getProtocol_device().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BPMN_translatorPackage.MQTT_DEVICE__PROTOCOL_DEVICE:
        getProtocol_device().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BPMN_translatorPackage.MQTT_DEVICE__PROTOCOL_DEVICE:
        return protocol_device != null && !protocol_device.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (protocol_device: ");
    result.append(protocol_device);
    result.append(')');
    return result.toString();
  }

} //mqtt_deviceImpl
