/**
 * generated by Xtext 2.23.0
 */
package org.xtext.bPMN_translator.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.bPMN_translator.BPMN_translatorPackage;
import org.xtext.bPMN_translator.Singleton;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Singleton</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SingletonImpl extends TagImpl implements Singleton
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingletonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BPMN_translatorPackage.Literals.SINGLETON;
  }

} //SingletonImpl
